### ISSUE TITLE
docs is not configured with asciidoctor to render html entities

### ISSUE THREAD

**Issue by dlloyd09** [cs50/docs#5]
e.g. &times; or &#215; to render the multiplication cross symbol no longer works, and I imagine also that other HTML entities may no longer work as well?

**Comment by dlloyd09** [comment]
Ha, it rendered my stuff! That's & times; (no space) or &# 215; (no space)

**Comment by dmalan** [comment]
Have an example? I just rendered

```
---
title: test
---

What is A &times; B?
```

and got:

<img width="531" alt="screen shot 2016-09-11 at 12 23 05 pm" src="https://cloud.githubusercontent.com/assets/788678/18418766/85e911fa-781a-11e6-8d78-9aaea04641aa.png">

**Comment by dlloyd09** [comment]
The pennies AP spec was not rendering it right. I just changed it to "x",
but here's a screenshot of what I was seeing (&times; was doing the same
thing)

[image: Inline image 1]

**Comment by dmalan** [comment]
I'm seeing (on an old version):

<img width="495" alt="screen shot 2016-09-11 at 12 28 54 pm" src="https://cloud.githubusercontent.com/assets/788678/18418824/5ff74d4e-781b-11e6-98cc-0be59642682a.png">

Is that what you mean? Know what character you pasted into the .adoc itself? In `vim` I see the same funky question marks. (Not sure what unicode char it's trying to be.)

**Comment by dlloyd09** [comment]
The old version is what triggered me to fix. When I opened in `atom` I also saw the question marks, but then I found and replaced with the HTML entity.

**Comment by dlloyd09** [comment]
I'm converting back to &times if you want to see what I see.

**Comment by dmalan** [comment]
Can you paste in literally the times symbol, ×? Best not to embed HTML entities in AsciiDoc, since it then ties us to HTML output, breaking, e.g., potential PDF rendering.

But if you do need to use HTML entities in `source` blocks, to avoid:

<img width="184" alt="screen shot 2016-09-11 at 12 33 00 pm" src="https://cloud.githubusercontent.com/assets/788678/18418849/efc042c8-781b-11e6-803a-3e6ae1fe756d.png">

from:

```
[source]
----
2 &times; 3
----
```

you can do:

```
[source,subs=quotes]
----
2 &times; 3
----
```

Source: http://asciidoctor.org/docs/user-manual/#quotes

**Comment by dlloyd09** [comment]
Pasting in the entities seems to work!
